[package]
name = "d-mark"
version = "0.1.0"
authors = ["Denis Defreyne <denis@denis.ws>"]
description = "Parses D*Mark files"
categories = ["parser-implementations"]
license = "MIT"

[dependencies]
clap = "2.32.0"

[badges]
maintenance = { status = "experimental" }
